### PR TITLE
Bump metals version to 0.9.6

### PR DESCRIPTION
**Pull request by ckipp01**

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks for the update! I will try to move it to scalameta today.

**Comment by tgodzik** [comment]
@ckipp01 it's now moved to scalameta/gitpod-sample

The prebuilds I don't think are correctly configured yet and we could spend some time to improve the gitpod support, but I will mso tlikely not have time to do it now.

**Comment by ckipp01** [comment]
> @ckipp01 it's now moved to scalameta/gitpod-sample
> 
> The prebuilds I don't think are correctly configured yet and we could spend some time to improve the gitpod support, but I will mso tlikely not have time to do it now.

Cool, thanks for moving it over. I'll see if I can get a bit of time to play around with it. From what I could tell though when testing so far is that it does work pretty well!

Is it possible to change the name to be more descriptive? It'd be nice for someone to read it and know exactly what the it's a gitpod sample of. Can it instead be `gitpod-metals-sample` or `metals-gitpod-sample`? I think those are a bit more clear.

**Comment by tgodzik** [comment]
Sure! changed to `metals-gitpod-sample`

**Pull request merged**
